name: release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Tipo de incremento: patch, minor, major ou pre*'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

permissions:
  actions: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.19.0
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(npm version "${{ inputs.increment }}" -m "chore(release): v%s")
          git push --atomic origin HEAD:main "${tag}"
          gh workflow run publish.yml --ref "${tag}"
